# Generated by Django 4.1.2 on 2023-05-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unittrustinvestment',
            name='agent_contact_no',
        ),
        migrations.RemoveField(
            model_name='unittrustinvestment',
            name='agent_name',
        ),
    ]
