# Generated by Django 4.1.2 on 2023-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_unittrustinvestment_agent_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittrustinvestment',
            name='agent_contact_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='unittrustinvestment',
            name='agent_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
