# Generated by Django 4.1.2 on 2023-05-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_notifier_accesslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='spa_price',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='socso',
            name='account_value',
            field=models.FloatField(blank=True, max_length=128, null=True),
        ),
    ]
